name: CI with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Passos do job de testes
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test  # Este job só vai rodar depois do job 'test'
    steps:
      # Passos do job SonarCloud (como o arquivo sonar.yml que você já tem)
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com cobertura
        run: |
          pytest --cov=principal --cov-report=xml
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          sonar-project-key: Taveirasson_Trabalho-Teste-de-software-faculdade
          sonar-organization: taveirasson
          sonar-host-url: https://sonarcloud.io
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar-python.coverage.reportPaths: coverage.xml
