name: Build
on:
  push:
    branches:
      - master
      - minha-branch-de-teste
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: 
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk 
          sudo apt-get install -y unixodbc-dev  
      - name: Install tox and any other packages
        run: |
          pip install tox
          pip install pytest
          pip install pytest-cov 
          pip install pyodbc
      - name: Generate Reports
        run: export PYTHONPATH="${GITHUB_WORKSPACE}/principal" 
      - name: Run tox
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.python.coverage.reportPaths=.github/workflows/coverage-reports/coverage.xml