# .github/workflows/build.yml
name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Para garantir que o histórico completo seja recuperado

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Instalar dependências
      - name: Instalar tox e dependências
        run: pip install tox

      # 4. Executar tox para rodar os testes e gerar o relatório de cobertura
      - name: Rodar Tox
        run: tox -e py39

      # 5. Rodar a análise do SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Defina seu token no GitHub Secrets
